### ISSUE TITLE
Add Support for LIKE (Regexp)

### ISSUE THREAD

**Issue by brett19** [couchbaselabs/gojsonsm#19]
JSONSM should support performing filtering based on a regexp string match.  This is an issue to track ownership, requirements and implementation.

**Comment by brett19** [comment]
There is a known requirement here that negative lookahead is supported.  This may require the use of a third-party regexp library as opposed to the library bundled in the golang stdlib.  An alternative option would be to introduce various hooks to enable custom operators to be supported, or alternatively custom transforming or matching.

**Comment by brett19** [comment]
I think we can do this quite simply by adding a new LikeExpr (which accepts a FastVal as the RHS) along with a `Compiled Regexp` FastVal for performance.

**Comment by nelio2k** [comment]
>>> strings could be used for non-precompiled ones) for performance

But when users specify things coming in via `ParseJsonExpression`, they will be specifying a string regardless. How do we know whether it's a string or regular expression? Since any valid non-regex string can be pre-compiled into regex?

**Comment by nelio2k** [comment]
Closing issue as Regex support has been added.
