### ISSUE TITLE
Matcher and simpleParser to support Time based comparison

### ISSUE THREAD

**Issue by nelio2k** [couchbaselabs/gojsonsm#68]
One of the functions that would be good to have is to have time comparisons in the matcher.
The thinking behind is to have a new type of FastVal called "TimeValue", which will hold a golang Time struct, and time provides us comparators of Before, After, Equal, etc. We'll be sticking with the RFC-3339 format that is used in the golang time library, since N1QL uses ISO-8601, but Golang doesn't directly support ISO-8601.

The miss here is that a lot of documents may have the values of "YYYY-MM-DD" and we can't do matching on that. Perhaps we can address that in another PR/issue. Is there a good way to address this at this point, though?

For the corner cases where we're doing different scope of time comparison, we will just simply pass in and let time library do comparison. For example:
If user is checking for a field is equivalent to a time: "2018-11-21T00:01:02Z", but the document field has the actual time value of "2018-11-21T00:01:02.03Z", the the Equal() operator will return false. 

The workaround is for user to specify a range that covers that specific time in the document, as we don't want to spend the resources guessing the user's intent.

**Comment by brett19** [comment]
There will need to be a function that takes a string and returns a TimeValue to enable field<->field comparisons.
